version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=NOTES_API
      - POSTGRES_USER=rafael
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/data/postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80